title: Project title in sentence case
hero_image: images/banner.png
description: A short description of the project
listed: false
pdf: false
steps:
  - title: What you can make
  - title: Choose a Scratch backdrop
  - title: Draw a Scratch backdrop
  - title: Upload your own backdrop
  - title: Add a Scratch sprite
  - title: Draw a Scratch sprite
  - title: Upload your own sprite
  - title: Make your sprite fly
  - title: Make your sprite run and jump
  - title: Aim - get to a goal
  - title: Aim - collect things
  - title: Aim - defeat enemies

